import Head from 'next/head';
import dbConnect from '../utilities/dbConnect';
import { useRouter } from 'next/router';

const Home = ({ notes }) => {
  // console.log("notes:", notes);
  const router = useRouter();

  const handleView = (note) => {
    console.log(note);
    router.push(`/${note._id}`)
  }

  return (
    <div>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid xl:grid-cols-4 md:grid-cols-2 gap-6">
        {notes.map((note,index) =>
          <div key={`${note}-${index}`} className="card border flex flex-col justify-center m-5 cursor-pointer">
            <div className="flex justify-center mb-5 p-2 border-b-2 border-solid border-gray ">
              {note.title}
            </div>
            <div className="flex justify-center p-2">
              {note.description}
            </div>
            <div className="card-footer my-5 mx-2">
              <button
                onClick={() => handleView(note)}
                className="bg-cyan-600 hover:bg-cyan-500 text-white p-2 m-2 rounded w-1/5"
              >
                View
              </button>
              <button
                onClick={handleView}
                className="bg-cyan-600 hover:bg-cyan-500 text-white p-2 m-2 rounded w-1/5"
              >
                Edit
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default Home;

export async function getStaticProps(context) {
  const res = await fetch('http://localhost:3000/api/notes');
  const { data } = await res.json();
// console.log(data)
  return {
    props: {
      notes: data
    }
  }
}